### PR TITLE
Remove revoked and deprecated techniques

### PR DESCRIPTION
**Pull request by nicoledozo**
Hey there,
I've noticed that the matrix was not quite up-to-date and some deprecated and revoked techniques were present, so here is a quick update :)
Nicolas

### CODE REVIEW

**Comment by alatif113** [comment]
Thanks, looks good. Merged!

**Comment by nicoledozo** [comment]
Hey there !
The tactics and techniques are indeed up-to-date in the json files and in appserver/static/visualizations/mitre_attck_heatmap/src files.
However,  there still seems to be some leftovers in **visualization.js**.
Therefore when we use the visualization it still displays revoked and deprecated techniques
For example, technique _T1086 (Powershell)_ is deprecated and should not be displayed

Thanks for the work anyway !
Nicolas

**Comment by alatif113** [comment]
I forgot to rebuild the source code after incorporating the updated files. This should be done in the latest 1.8.0 release. Thanks for the help. Let me know if there are still issues.

**Comment by nicoledozo** [comment]
Hello !
Unfortunately it seems that old techniques are still present in the following files, therefore displayed in the matrix 

appserver/static/visualizations/mitre_attck_heatmap/build/enterpriseAttack.js
appserver/static/visualizations/mitre_attck_heatmap/src/enterpriseAttack.js
appserver/static/visualizations/mitre_attck_heatmap/visualization.js

Thank for your work :)
Nicolas

**Comment by alatif113** [comment]
Sorry looks like I missed a step again. I was previously building the json files in the bin directory and manually copying them over to the build directory, which I forgot to do. I updated the code to generate the files directly in the build directory when running the enterpriseAttack2json.py script. Should be fixed in the 1.8.1 version. 

This still requires a step of building everything with npm run build to combine and condense all the code into the visualization_source.js file. Try it out now and let me know if there are still issues.

**Comment by nicoledozo** [comment]
Seems all good now, thanks !

**Pull request merged**
